name: adora-belle
license: "AGPL-3"
description: Dispatcher for the webrtc-golem-trust

ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - adora-belle
      - hspec
      - http-client
      - http-types
      - servant-client
      - warp >= 3.2.4

library:
  source-dirs:
    - src

executables:
  adora-belle:
    main: exe/Main.hs
    dependencies:
      - adora-belle
    ghc-options:
      - -rtsopts
      - -threaded

dependencies:
  - aeson
  - base
  - bcrypt
  - bytestring
  - containers
  - either
  - filepath
  - htoml
  - memory
  - optparse-applicative
  - parsec
  - random
  - servant
  - servant-auth
  - servant-foreign
  - servant-server
  - stm
  - text
  - time
  - transformers
  - utf8-string
  - uuid
  - wai
  - wai-extra
  - wai-logger
  - warp
